### ISSUE TITLE
User Interface Rapid Prototyping V1.0

### ISSUE THREAD

**Issue by lyz9518** [JiJiU33C43I/UCI-Schedule-Assistant#4]
Here attached the sample of our user interface. Feel free to add comment or suggest changes.

--Arthur

![ui_sample](https://user-images.githubusercontent.com/44278886/50321016-d8b38900-0509-11e9-92d3-0e990bba2bb3.png)

**Comment by Jasonhx612** [comment]
Maybe user should be able to also choose a course from a drop-down list

**Comment by Jasonhx612** [comment]
This UI looks like it doesn't include instructor's name. it's will be great to list instructor's name and a link to its rate my professor page.

**Comment by lyz9518** [comment]
>           Maybe user should be able to also choose a course from a drop-down list
We can have the drop down list option but I would say list all of them on the front page as well to give them an overall look. But yeah we can definitely add it.

**Comment by tezktenr** [comment]
Sorry for the late feedback. This is a really GOOD START and a fantastic UI design. I really like your idea of using the progress bar to indicate the number of people enrolled in the course. That is a brilliant and a fancy and modern DESIGN DECISION. That design will definitely be kept throughout our UI Design for this project. 

However, I still think there are so many things to improve and to talk about in our following UI design progress, so keep it up, guys. Even though I am not as deficient in UI/UX design as writing code, below are some of the opinions or suggestions I have for our current UI design.
First of all, let me present my rough, boring, and plain UI paper prototype as follows:
![wechat screenshot_20181223002138](https://user-images.githubusercontent.com/39232681/50376602-0e5f8b80-064a-11e9-8589-1caeee37283e.png)

### Suggestions and Feedbacks:
* I suggest using the common drop down menu bar (![wechat screenshot_20181223003304](https://user-images.githubusercontent.com/39232681/50376626-6e563200-064a-11e9-8b94-1df59fc29868.png)) to display "function tags" instead of listing them vertically as in your Prototype V1.0. 
    * Here, I am referring to the tags that say "search class", "View my Schedule", "Class Extended", etc. If I am understanding your prototype correctly, I am assuming that these are the different "function" tags _(where users can click on and get to different pages and use the different functions of this software)_, correct? 
    * The reason of me suggesting the common drop down menu bar is anticipation of CHANGES. We would never know how many of those function tags we need AT THE TIME WHEN we are designing/writing the UI. We may add more functions to our app, requiring more tags, even after the release. If we are to add MORE function tags to our app , we may need to do more adjustments to our general UI screen in the future using the vertical listing scheme (like vertical sizes of the screen need to be increased). Thus, I suggest using the drop-down menu bar due to the fact that it is more flexible when we would like to change in the future
    * _Note: I am not saying that the vertical listing scheme would not work (In fact, you may add a scroll down bar to solve this problem if you persist to use vertical listing). I am just saying this design may not be as elegant as the common 3-hyphen drop down menu bar_. 

* I suggest NOT including the "sign up/ login" functions on the upper right corner at the present phase. I suggest replacing it with the one that I choose, which is just asking for the users' email address. There are several reasons behind my suggestions:
    * We simply just do not have the resource (like servers) or funding to support the account record memory&tracking system and the signup/ login function. Even though this may be a COOL THINGS TO TRY and LEARN and it is definitely in my wish list!!
   * Further thinking about the issue, I realize that we simply may not need the users to have an account and we may not need their user profile/info. Think about it : which functions/current proposed functions of our app would actually need to track users' status and profile? Probably NONE. Our app CURRENTLY does not have a social function. The only function that may require the user status/profile is "AUTOMATIC COURSE SELECTION", which requires our app to track users' Webreg account and password (security being another great issue here: how are we gonna let the users trust us and input their webreg(UCI-NetID) passwords? Thus, "automatic course selection" is called our ULTIMATE goal). For all the other basic viewing schedule functions, a user account is redundant. For notification feature, I suggest capturing the users' email address and our app can send an email to them (let's say, as long as a course is open for all majors). Capturing only the user's email address as input may not cause such a HIGH SECURITY CONCERN ISSUE as capturing their webreg passwords. 
    * For _temporary and quick_ development, I would think replacing the account function with the email address capture function is a WISE decision. For the purpose of releasing our functions as soon as possible, the account function is way too complicated. 


### A Few Words about Future UI Design and Development for this Project: IMPORTANT!!
As can be seen above, I used way too many words to convey my meaning and you may not even read all of them carefully at this point. It may be that I am the kind of person who are just too talkative. However, we have to admit that this method of communication and collaborative UI design & prototype is so INEFFICIENT.
* I have to use a lot of pictures (like the 3-hyphen drop down menu bar) during communication. This is so much trouble doing it using the method here.
* I simply can't convey my exact meaning by just uploading my paper prototype without explaining it. The paper prototype is STATIC, meaning that it cannot change or interact with you. You don't know which one is button and you cannot click on everything to see what happen and what I mean when I draw it out on paper. Thus, it may be hard for you to even understand what the 3-hyphen drop down menu is by just looking at my paper prototype without seeing my explanation.
* Also, say you want to see how the different pages look like when users click/select on the different "function tags". YOU CAN'T DO IT SIMPLY. You have to draw MULTIPLE pictures and explain it to me using words because I might not know which click jumps to which picture. Paper/Drawing prototype is STATIC, which is dumb.

All of those MIGHT BE SOLVED EASILY using a designated/professional software UI prototype tools. In this project, I suggest that we using the adobe XD CC, which is a completely free UI prototype tools. It supports DYNAMIC UI prototype. For more details, please check out the [UI Design sub-page](https://github.com/JiJiU33C43I/UCI-Schedule-Assistant/tree/master/UI%20design) of this project. As an example, this is a prototype of the V1.0 prototype as above, produced using adobe XD CC. You may simply click on the following link to interact with the prototype without downloading adobe XD CC: [https://xd.adobe.com/view/0fd50d34-fe1a-4908-69e5-cfd4d9ed55ef-79e4/](https://xd.adobe.com/view/0fd50d34-fe1a-4908-69e5-cfd4d9ed55ef-79e4/). Try to click on the "_Search Class_" or "_View My Schedule_" to see the idea behind using this tool.

**Comment by tezktenr** [comment]
In the future, a new "prototype layout discussion" issue will be created when a new prototype is finished. Then, the old issue will be closed. For example, if prototype V1.01 is finished, then this issue will be closed while a new one called "UI Prototype V1.01" will be created. In that new issue, the adobe xd prototype link will be attached and we may discuss and give feedbacks on that.

**Comment by Jasonhx612** [comment]
> In the future, a new "prototype layout discussion" issue will be created when a new prototype is finished. Then, the old issue will be closed. For example, if prototype V1.01 is finished, then this issue will be closed while a new one called "UI Prototype V1.01" will be created. In that new issue, the adobe xd prototype link will be attached and we may discuss and give feedbacks on that.

I don't know if this is what you want: https://xd.adobe.com/view/37b01278-c267-4e14-6b6d-032746e228c8-4181/

**Comment by tezktenr** [comment]
A new prototype has been released and this issue will be closed. For the next version of the UI Prototype, refer to: https://github.com/JiJiU33C43I/UCI-Schedule-Assistant/issues/6
